version: "3.7"

services:
  app:
    container_name: edfhr_server
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "80:8000"
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db
